FirstInstance:
  Skip: false
  # this one here is super important! key will not get generated if path not set
  MachineKeyPath: /zitadel/secrets/machine-key.json # the path where the generated machine key is stored on zitadel instance
  InstanceName: ZITADEL
  DefaultLanguage: en
  Org:
    Name: MyTestOrg
    Human:
      UserName: admin
      Password: Password1!
      PasswordChangeRequired: false
      FirstName: Admin
      LastName: Admin
      Email:
        Verified: true
      PreferredLanguage: en
    Machine:
      Machine:
        # for some reason the machine key will only be generated if a machine user is created
        UserName: admin-sa
        Name: admin-sa
      # necessary to create a machine key
      MachineKey:
        Type: 1