services:
  zitadel:
    restart: 'always'
    networks:
      - 'internal'
    image: 'ghcr.io/zitadel/zitadel:v2.56.0-rc.1'
    command: >
      start-from-init
      --config /zitadel/config/defaults.yaml
      --steps /zitadel/config/init-steps.yaml
      --masterkeyFile /zitadel/secrets/masterkey.txt
      --tlsMode disabled
    volumes:
      - ./zitadel/config:/zitadel/config:ro
      - ./zitadel/secrets:/zitadel/secrets:z
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "/app/zitadel", "ready", "--config", "/zitadel.yaml" ]
      interval: '10s'
      timeout: '5s'
      retries: 5
      start_period: '10s'

  db:
    restart: 'always'
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zitadel
    networks:
      - 'internal'
    volumes:
      - ./../local/zitadel-db:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '5432:5432'

networks:
  internal: